condense_wildcard_suffixes = true
error_on_line_overflow = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
report_fixme = "Always"
report_todo = "Always"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
